USB_VID = 0x1209
USB_PID = 0xBD00
USB_PRODUCT = "librelab::Big Dot"
USB_MANUFACTURER = "UVA SDS"

CHIP_VARIANT = SAML21E18B
CHIP_FAMILY = saml21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

CIRCUITPY_ANALOGIO = 1
CIRCUITPY_PWMIO = 1
CIRCUITPY_BUSIO = 1
CIRCUITPY_BUSDEVICE = 1
CIRCUITPY_I2CPERIPHERAL = 1
CIRCUITPY_MATH = 1
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_RANDOM = 1
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_ROTARYIO_SOFTENCODER = 0
MICROPY_PY_ASYNC_AWAIT= 0
CIRCUITPY_USB_HID = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_BOARD = 1
CIRCUITPY_OS = 1
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_USB_MIDI=0
SUPEROPT_GC=0

# Include these Python libraries in firmware.
#FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_RFM9x
