USB_VID = 0x1209
USB_PID = 0xBAB3
USB_PRODUCT = "Bast SAML21"
USB_MANUFACTURER = "Electronic Cats"

CHIP_VARIANT = SAML21G18B
CHIP_FAMILY = saml21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
